version: 0.0
os: linux
files:
  - source:  ./reqres_products-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/reqres_products/

permissions:
  - object: /home/ubuntu/reqres_products
    pattern: "**"
    owner: ubunutu
    group: ubuntu
    mode: 750
    type:
      - file

hooks:
  pplicationStart:
    - location: start_server.sh
      runas: ubuntu
  ApplicationStop:
    - location: stop_server.sh
      runas: ubuntu
